import React from "react";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "@/config/theme";
import Head from "next/head";

interface IProviderProps {
  children?: React.ReactNode;
}

const Provider: React.FC<IProviderProps> = (props) => {
  return (
    <>
      <Head>
        <title>TASI Galicia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://onlinebanking.bancogalicia.com.ar/Images/favicon.ico"
        />
      </Head>
      <ThemeProvider theme={theme}>
        {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
        <CssBaseline />
        {props.children}
      </ThemeProvider>
    </>
  );
};

export default Provider;
